name: Deploy to Lightsail

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Node.js 설치 및 빌드
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      # 3. AWS CLI 설정
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  # 해당 AWS 리전

      # 4. Lightsail에 배포
      - name: Deploy to Lightsail
        run: |
          aws lightsail push-container-image --service-name humorie-frontend \
            --image image_name:latest --label latest

      # 5. Lightsail 서비스 업데이트
      - name: Update Lightsail Service
        run: |
          aws lightsail update-container-service \
            --service-name humorie-frontend \
            --public-endpoint json_file_with_config
