name: Deploy to Lightsail

on:
  push:
    branches:
      - main # main 브랜치에 푸쉬할 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 18 설치
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 프로젝트에 맞는 Node.js 버전 설정
          cache: 'yarn' # Yarn 캐시 활성화

      # 3. 의존성 설치 및 빌드
      - name: Install dependencies and build
        run: |
          yarn install
          yarn build

      # 4. Lightsail 서버로 파일 전송
      - name: Deploy to Lightsail
        env:
          LIGHTSAIL_IP: ${{ secrets.LIGHTSAIL_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/lightsail.pem
          chmod 600 ~/.ssh/lightsail.pem
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/lightsail.pem ubuntu@$LIGHTSAIL_IP "rm -rf /var/www/html/*"
          scp -o StrictHostKeyChecking=no -i ~/.ssh/lightsail.pem -r ./dist/* ubuntu@$LIGHTSAIL_IP:/var/www/html
